spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj_db
    username: oj_admin
    password: oj_token
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.edu.oj.entity
  