spring:
  application:
    name: oj-application
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/oj_db
    username: oj_admin
    password: oj_token
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: judge-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.edu.oj.entity


logging:
  level:
    web: DEBUG
  