spring:
  application:
    name: oj-application
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/oj_db
    username: oj_admin
    password: oj_token
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.add.type.headers]": false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.json.value.default.type]": "com.edu.oj.message.ResultMessage"
    topic:
      submission: submission-queue
      result: judge-result

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.edu.oj.entity

logging:
  level:
    web: DEBUG

server:
  port: 8080
  servlet:
    session:
      timeout: 60m

s3:
  endpoint: http://localhost:8333
  region: us-east-1
  access-key: admin
  secret-key: admin
  bucket: oj-data